apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  strategy: {}
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: 065548663792.dkr.ecr.eu-north-1.amazonaws.com/payments:latest
        name: production
        env:
          - name: PORT
            value: "3001"
          - name: NOTIFICATIONS_HOST
            value: notifications # name of the service
          - name: NOTIFICATIONS_PORT
            value: "3000"
          - name: STRIPE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: stripe
                key: apiKey
        ports:
          - containerPort: 3001
