apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy: {}
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: europe-central2-docker.pkg.dev/sleepr-437321/auth/production
        name: production
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt
                key: jwtSecret
          - name: JWT_EXPIRATION
            value: "3600"
          - name: HTTP_PORT
            value: "3003"
          - name: TCP_PORT
            value: "3002"
        ports:
          - containerPort: 3002
          - containerPort: 3003

