version: '3.8'
services:
  e2e:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: europe-central2-docker.pkg.dev/sleepr-437321/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: europe-central2-docker.pkg.dev/sleepr-437321/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: europe-central2-docker.pkg.dev/sleepr-437321/payments/production
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'
  notifications:
    image: europe-central2-docker.pkg.dev/sleepr-437321/notifications/production
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'
  mongo:
    image: mongo
